name: Automatic conversion subscription

on:
  push:
  schedule:
    - cron: '0 2 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: run
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}
          URL: ${{ secrets.URL }}
        run: bash ./ACS.sh
