name: Automatic conversion subscription

on:
  push:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: run
        env:
          github_token: ${{ secrets.TOKEN }}
          repository: ${{ secrets.REPOSITORY }}
          email: ${{ secrets.EMAIL }}
          name: ${{ secrets.NAME }}
        run: bash ./ACS.sh